### ISSUE TITLE
Select2 needs "and 300 more..." in the dropdown

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#39]
When you use select2 as a dropdown, you get the illusion that there is only 10 records to choose from. 

Need to have some indicator that there are many other options that can be found using text type-ahead. 

Something like "and 300 more" on the last item of the select when you just use it as a drop down..

**Comment by kchapple** [comment]
@ftrotter To me, the bug appears to be that the list doesn't display all the results if you have no filter applied... Looking into this one.

**Comment by kchapple** [comment]
@ftrotter  I see the issue here. But If we have a large result set, for some reason, Laravel runs out of memory on my system (128MB) when requesting all models on the nonprofitcorp table, so that's no good, but I think a better solution is to use pagination in the select2 control, so when you scroll down in large data sets, the data keeps coming.

**Comment by kchapple** [comment]
@ftrotter let me know if this works, donation model, with the nonprofit relation will provide a good demo. Basically, it scrolls infinitely. Now even if there are more than 20 results in your search query, you can still view them all.
![Screen Shot 2019-12-17 at 4 13 14 PM](https://user-images.githubusercontent.com/271809/71034818-37ddb680-20e8-11ea-8d5d-604cb3de7b54.png)

**Comment by ftrotter** [comment]
excellent, will roll into testing!!

**Comment by seanccsmith** [comment]
This works! Closing issue.
