### ISSUE TITLE
Multiple missing js and css assets

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#40]
Looking at the network tab in chrome developer mode. 

<img width="691" alt="durc_missing_libraries" src="https://user-images.githubusercontent.com/83133/49279580-82dd4b00-f44d-11e8-9081-3b110f5d4be0.png">

**Comment by kchapple** [comment]
I think I must have fixed this a while back and forgot to mark it, because there are no longer missing assets. The ones that were missing were brought into the project and are exported during the "php artisan vendor:publish --tag=public" command. Others, like bootstrap and fontawesome are hosted on CDNs. From what I understand, it is accepted best practice to utilize CDNs and potentially use a local copy as a backup, but that is probably a separate issue. @ftrotter Let me know if that's what you'd like to do for 1.0, or just leave as-is?

**Comment by seanccsmith** [comment]
No JS or CSS assets reported missing on any page within Lore Commander. Closing issue.
