### ISSUE TITLE
1.0 refactoring

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#46]
The current version of DURC will auto-generate Zermelo lists. 
It also has functions that can be used in other templates to link to all zermelo list and DURC create forms for every datatype. 

This makes having a "left menu" on the DURC data editor page redundant. 
Instead, the "go back to list" function should return to the generated Zermelo list. 

As nice as it is to have a list of all other DURC objects when you are editing object of type goodperson or car (etc) for security purpose it is probably best to not have the links to all of the objects from all of the objects.. so I think that means eliminating the left side menu from all DURC interfaces. 

Optional: 
The Zermelo generation code works, but it is very "meta" where it uses DURCs notions of object self awareness to reverse engineer how to create good MapRow links for all of the fields that are gotten to by visiting other tables... But the better approach might be to just figure out what the actual value are at compile time and then hard code them so that the resulting Zermelo report is readable and understandable, and something that can be used as a starting point for a  useful custom report. 

Other than these items, I think that the plan for 1.0 with DURC is just to get all of the extant bugs fixed and to implement those few critical features that are used all the time. There is a 1.0 requirement tag that I have deployed on the github issue tracker for both Zermelo and DURC that should present a useful discussion point for what needs to be sorted for a 1.0 release.

**Comment by kchapple** [comment]
> having a "left menu" on the DURC data editor page redundant

I'm not sure how Zermelo Datatables make the left menu redundant, since it show a list of all database object types, not all objects of a particular type as Zermelo does. I think I might be misunderstanding you. Maybe we need to have a quick call about what you mean in this issue #46.
> eliminating the left side menu from all DURC interfaces.

 I get the concern, but maybe the access should be configurable by a authorization system rather than just remove it entirely? It is nice to have, otherwise, I feel like it may be difficult or impossible to navigate?

**Comment by seanccsmith** [comment]
Has this been done? I'm not seeing anything that could be described as a left menu on the data editor page, so maybe we can just close this??
