### ISSUE TITLE
Four digit year problem

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#56]
cropping up everywhere...

**Comment by seanccsmith** [comment]
When trying to create a new entry in a Lore Commander report, upon trying to save the new data DURC returns this error. It is suspected that this is an issue with the autofilled created_at and/or updated_at fields rather than user input.


![Screen Shot 2020-04-29 at 5 09 46 PM](https://user-images.githubusercontent.com/42678849/80724295-4c36b480-8ac7-11ea-9887-84bbd5e7f90b.png)

**Comment by seanccsmith** [comment]
Dates seem to be generating correctly now. Closing this issue.

**Comment by ftrotter** [comment]
Happily, just confirmed that an un-updated version of DURC failed at this, but the current DURC does not!!
