### ISSUE TITLE
Using getNameField for the DURC editing pages

### ISSUE THREAD

**Issue by ftrotter** [CareSet/DURC#79]
The method used to populate the name in the DURC web form drop down is not tying back to the DURCModel->getNameField() function to sort out which name should display. Is this something that can be fixed? https://github.com/CareSet/DURC/blob/master/src/DURCModel.php#L308

To see the problem look at onering url /DURC/podproject/1016 and look at the project repo id field... It should be finding the repoName field but it is not...

**Comment by kchapple** [comment]
@ftrotter is this related or a dup of #76 ?

**Comment by kchapple** [comment]
To fix that, I used the same code in the search function of the controller (which displays the results list in the select2 dropdown) but I can replace that search function and the field display function with the result of Model::getNameField()

**Comment by kchapple** [comment]
I re-ran durc and there seems to be a bug causing those two repo fields not to get their display values, and is crashing the select2 plugin. Plan of action is to 1: Fix bug 2: refactor so all of the "select text"  comes from the getFieldName() function, rather than the controller functions. 
<img width="1224" alt="Screen Shot 2020-09-08 at 10 06 09 AM" src="https://user-images.githubusercontent.com/271809/92487459-4199d380-f1bb-11ea-999c-8c6d45bdab3b.png">

**Comment by kchapple** [comment]
@ftrotter I fixed the bug that was causing the select2 to not function. Now it pulls correctly from the related model using the controller code. I didn't make it look for the "local" name field from the same table. That seems weird to me from a relational DB standpoint, because if you update the project repo, then you'd also always have to update the repo name, which is already on the related model's table, so not sure why you'd even need the repo name field, or it shouldn't it be on the related model. Bug was in the mustache generator for select2, so will need to re-write views.
<img width="1299" alt="Screen Shot 2020-09-08 at 11 39 43 AM" src="https://user-images.githubusercontent.com/271809/92498106-37320680-f1c8-11ea-9101-3c88fbe49ace.png">

**Comment by seanccsmith** [comment]
Did we decide that this is a dup of #76 ? If so this looks good and can be closed.

**Comment by seanccsmith** [comment]
If I'm understanding this correctly, this looks like it's working as expected.
